/** Client-facing path for the persisted model owned by the shared schema. */
export type {
  AppData,
  Goal,
  HistoryItem,
  Interval,
  MonthPlanning,
  MonthTemplateRule,
  MonthTemplateSchedule,
  Note,
  NoteColor,
  PeriodReview,
  ReviewPeriod,
  ReviewPeriodKind,
  ReviewResult,
  Rule,
  Task,
  TaskColor,
  TaskGroup,
} from '../src/shared/data-schema';
